### ISSUE TITLE
讚數出問題

### ISSUE THREAD

**Issue by popnfamily** [wake/kpopn-ninja#1]
我們的人員 Glenda report 的：

這篇讚數出問題：http://kpopn.com/2015/04/20/271529/
Glenda: 但我早一點看的時候還是好的，不知道準確出錯的時間

她的 FB 除錯頁面：http://i.imgur.com/gWAmRJ2.jpg
Glenda: 這是除錯後的結果，所以不知道可不可以從框框那邊推知是兩小時前發生的事情？

**Comment by wake** [comment]
@popnfamily 所以原本好的是指讚數有集中在 http://kpopn.com/2015/04/20/271529/ 這個網址上嗎？

感覺越來越詭異了，我會開始用工具來定時截圖紀錄情況…

**Comment by popnfamily** [comment]
是的! 原本有集中在那個網址～～

謝謝捏～

**Comment by wake** [comment]
咦？我剛剛發現 http://kpopn.com/2015/04/20/271529/ 這個網址應該是在安裝 plugin 之前就上線了的，因為還可以看到短網址出現

![](http://drop.wake.gs/hsSJ+)

**Comment by wake** [comment]
@popnfamily 我目前看到最後一篇還有短網址（外掛安裝前的最後一篇）是 [NU’EST 日文二單短版 MV](http://kpopn.com/2015/04/20/271495/) 

![](http://drop.wake.gs/O5bY+)

再麻煩幫忙注意一下從這篇之後的是否還有出現錯亂的情況。這隻 issue 我會先關閉起來，謝了。
