### ISSUE TITLE
Kpopn 搜尋功能無法使用

### ISSUE THREAD

**Issue by recorder7755** [wake/kpopn-ninja#9]
在 Kpopn 首頁、首頁以外的地方搜尋，結果是一片空白，電腦、手機結果一樣！

首頁搜尋框
![1](https://cloud.githubusercontent.com/assets/12045698/7718276/8cdc1c00-fee0-11e4-9ef3-633d620c2472.jpg)

首頁外搜尋
![2](https://cloud.githubusercontent.com/assets/12045698/7718277/8cfd7508-fee0-11e4-8c80-c78b248d4db3.jpg)

兩者結果一樣
![3_blank](https://cloud.githubusercontent.com/assets/12045698/7718278/8d3e5168-fee0-11e4-87f0-f5583cb22689.jpg)

**Comment by popnfamily** [comment]
我們 SNAP 不知道為什麼自己被關掉!! 問了 Kinsta 她們說不是他們~ 但找到了這個 error message, 似乎是我們搜尋壞掉的原因!!!

[Wed May 20 09:14:03 2015] [hphp] [17541:7fee20bff700:22995:000001] [] \nFatal error: <?php directive must be followed by whitespace, newline, or EOF (Line: 1, Char: 5)\nsyntax error, unexpected T_HH_ERROR, expecting $end in /www/kpopn_141/public/wp-content/themes/popn151y/search.php on line 1

**Comment by wake** [comment]
感謝 @popnfamily  提供的 error message，檔案已修正。搜尋功能已恢復正常。

**Comment by popnfamily** [comment]
@wake 實在是很穴穴你耶!

**Comment by recorder7755** [comment]
太~ 感~ 謝~ 啦~~
